apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: dev
  annotations:
    cert-manager.io/cluster-issuer: alitest-cluster-issuer
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - dashboard.alitest.site
      secretName: alitest1-site-tls   # ✅ matches your Certificate secret
  rules:
    - host: dashboard.alitest.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontendapp
                port:
                  number: 80
