apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backendapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Alialshemy/Devops_task.git  
    path: devops-manifest/backendapp                     
    targetRevision: main
    helm:
      releaseName: backendapp  
      valueFiles:
         - $values/devops-manifest/backendapp/values.yaml  

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
