apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Alialshemy/Devops_task.git  
    targetRevision: HEAD
    path: devops-manifest/cert
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd