apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Alialshemy/Devops_task.git  
    path: devops-manifest/nginx-ingress                     
    targetRevision: main
    helm:
      releaseName: ingress-nginx
      valueFiles:
         - $values/devops-manifest/nginx-ingress/values.yaml    

  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
