apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: oci://public.ecr.aws/karpenter/karpenter
      chart: karpenter
      targetRevision: "1.7.1"
      helm:
        releaseName: karpenter
        valueFiles:
          - $values/devops-manifest/karpenter/values.yaml
    - repoURL: git@github.com:Alialshemy/Devops_task.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: karpenter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
