name: Build, Scan & Push Backend to AWS ECR

on:
  push:
    branches:
      - main
    paths:
      - 'application/backend/**'
permissions:
  id-token: write
  contents: read

jobs:
  build-scan-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # ---------------- AWS Auth ----------------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5.0.0
        with:
          role-to-assume:  ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1
          audience: sts.amazonaws.com
          role-session-name: GitHubActionsSession
      # ---------------- ECR Login ----------------
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | \
          docker login --username AWS --password-stdin 167175811320.dkr.ecr.us-east-1.amazonaws.com

      # ---------------- Docker Build ----------------
      - name: Build Docker image
        run: |
          # Use Git SHA as tag
          TAG=${{ github.sha }}
          # Or uncomment below to use version number
          # TAG=v1.0.0
          IMAGE_URI=167175811320.dkr.ecr.us-east-1.amazonaws.com/backendapp:$TAG
          
          docker build -t backend-app ./application/backend/
          docker tag backend-app:latest $IMAGE_URI

      # ---------------- Trivy Scan ----------------
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 167175811320.dkr.ecr.us-east-1.amazonaws.com/backendapp:${{ github.sha }}
          format: table
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: os,library
          severity: CRITICAL,HIGH

      # ---------------- Push to ECR ----------------
      - name: Push Docker image to ECR
        run: |
          TAG=${{ github.sha }}
          IMAGE_URI=167175811320.dkr.ecr.us-east-1.amazonaws.com/backendapp:$TAG
          docker push $IMAGE_URI
