name: Build, Scan & Push Frontend to AWS ECR

on:
  push:
    branches:
      - main
    paths:
      - 'application/frontend/**'

permissions:
  id-token: write
  contents: write  # allow pushing back to repo

jobs:
  build-scan-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # ---------------- AWS Auth ----------------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5.0.0
        with:
          role-to-assume:  ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1
          audience: sts.amazonaws.com
          role-session-name: GitHubActionsSession

      # ---------------- ECR Login ----------------
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | \
          docker login --username AWS --password-stdin 167175811320.dkr.ecr.us-east-1.amazonaws.com

      # ---------------- Docker Build ----------------
      - name: Build Docker image
        run: |
          TAG=${{ github.sha }}
          IMAGE_URI=167175811320.dkr.ecr.us-east-1.amazonaws.com/frontendapp:$TAG
          docker build -t frontend-app ./application/frontend/
          docker tag frontend-app:latest $IMAGE_URI

      # ---------------- Trivy Scan ----------------
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 167175811320.dkr.ecr.us-east-1.amazonaws.com/frontendapp:${{ github.sha }}
          format: table
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: os,library
          severity: CRITICAL,HIGH

      # ---------------- Push to ECR ----------------
      - name: Push Docker image to ECR
        run: |
          TAG=${{ github.sha }}
          IMAGE_URI=167175811320.dkr.ecr.us-east-1.amazonaws.com/frontendapp:$TAG
          docker push $IMAGE_URI

      # ---------------- Update frontend values.yaml ----------------
      - name: Update frontend image tag in values.yaml
        run: |
          TAG=${{ github.sha }}
          YAML_PATH=devops-manifest/frontendapp/values.yaml
          yq eval ".image.tag = \"$TAG\"" -i $YAML_PATH

      # ---------------- Commit updated values.yaml ----------------
      - name: Commit updated values.yaml
        run: |
          TAG=${{ github.sha }}
          YAML_PATH=devops-manifest/frontendapp/values.yaml

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add $YAML_PATH
          git commit -m "Update frontend image tag to $TAG" || echo "No changes to commit"
          git push origin main
